import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-12 gap-6 h-screen p-10 text-center">
          <div className="lg:col-span-4 rounded-xl col-span-12 bg-black border border-gray-900 p-8">
            <Sidebar />
          </div>
          <div className="lg:col-span-8 rounded-xl col-span-12 bg-black border border-gray-900 p-8 flex flex-col gap-8">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
